# Generated by Django 3.2.4 on 2021-06-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
